### ISSUE TITLE
Error: `fsevents` unavailable (this watcher can only be used on Darwin)

### ISSUE THREAD

**Issue by winsmith** [cliqz/user-agent-ios#114]
## Expected Behavior
When running the app, the react native stuff should load.

## Actual Behavior
The green bar at the top stays, displaying "Loading from localost:8081...". Meanwhile in the Terminal, we see this error:

```

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/danieljilg/Repositories/bigfork 

Loading dependency graph...(node:44742) UnhandledPromiseRejectionWarning: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
(node:44742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:44742) UnhandledPromiseRejectionWarning: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
(node:44742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/sane/src/fsevents_watcher.js:37:13)
    at createWatcher (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:927:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:1092:44)
    at /Users/danieljilg/Repositories/bigfork/node_modules/jest-haste-map/build/index.js:463:23
```

**Comment by chrmod** [comment]
Can you please try to install watchman with brew? If this will help I will try to introduce Brewfile and add it to bootstrap.sh

**Comment by winsmith** [comment]
Installing watchman fixed it! Thanks!
